### ISSUE TITLE
[Bug] Custom search engines disappeared! Can't add any new ones! 

### ISSUE THREAD

**Issue by mackeev** [fork-maintainers/iceraven-browser#170] opened 2020-09-28 02:25 UTC
## Steps to reproduce
Add your own search engine BEFORE updating to 1.1, then update.

### Expected behavior
Your custom entry should be visible on the list (from my Nightly experience: sometimes you need to Quit and open the browser again)

### Actual behavior
Your custom entries will disappear from the list, BUT the browser remembers them! You can't add the same engine again. Or a new one, it won't go on the list.

### Device information

* Android device: redmi note 5 pro
* Fenix version: craven 1.1

**Comment by abhijitvalluri** [comment] 2020-09-28 23:07
Uh oh... We should look into it.

**Comment by abhijitvalluri** [comment] 2020-09-28 23:08
This is likely a duplicate of #166

**Comment by mackeev** [comment] 2020-09-29 00:50
For whatever reason, this particular bug was observed in the other day's Nightly: I could not add a new engine and left a bug report with the Fenix team. Yesterday (or today, for some) there was an update which resolved the issue with "old" custom engines  (they re-appeared), but my attempt to add a new one resulted in a crash. I was pretty persistent, and finally managed.
#166 is regarding v. 1.0, ain't it? I have no problem adding a new engine in 1.0 (I have it installed right now). The problem began in 1.1, when all the custom engines disappeared.

**Comment by mackeev** [comment] 2020-09-29 01:44
Yet another today's update fixed this issue in Nightly. No crashes when adding search engines.

**Comment by L31FY** [comment] 2020-10-01 00:46
It says I've added it but it doesn't appear and I can't use it. That's the bug I'm getting.

**Comment by mackeev** [comment] 2020-10-01 06:08
The problem returned in today's Nightly...
Managed to resolve it by killing (not quitting) the app a couple of times.

**Comment by interfect** [comment] 2020-10-04 04:02
I'm going to close this because #166 is the same problem.

**Closed as completed by interfect** 2020-10-04 04:02 UTC
Labels: bug, duplicate
