### ISSUE TITLE
Can you add a home button?  Just like Chrome and Edge?  That way we can return to the homepage quickly.

### ISSUE THREAD

**Issue by vaefly** [fork-maintainers/iceraven-browser#316] opened 2021-04-26 14:10 UTC
Can you add a home button?  Just like Chrome and Edge?  That way we can return to the homepage quickly.

**Comment by Madis0** [comment] 2022-02-11 14:19
Duplicate of #53 and exists in Iceraven 1.15.0 anyway.

**Closed as completed** 2022-02-12 16:13 UTC
Labels: needs:triage
