### ISSUE TITLE
Add AdNauseam extention

### ISSUE THREAD

**Issue by argentumiss** [fork-maintainers/iceraven-browser#579] opened 2023-03-02 00:40 UTC
https://addons.mozilla.org/en-US/firefox/addon/adnauseam/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by krystian3w** [comment] 2023-11-12 19:32
Other idea #684

**Comment by krystian3w** [comment] 2023-11-12 19:49
Duplicate of #337

**Closed as completed** 2023-12-09 16:29 UTC
Labels: needs:triage
