### ISSUE TITLE
Iceraven keeps running in the background after closed 

### ISSUE THREAD

**Issue by richie3011** [fork-maintainers/iceraven-browser#657] opened 2023-09-11 11:36 UTC
Iceraven browser running in background after I close it. It causes battery drain, I don't see this issue on Fennec F droid. I think this issue similar to #215

cc: @akliuxingyuan please investigate this issue

**Comment by akliuxingyuan** [comment] 2023-09-27 13:47
duplicate of #215

**Closed as completed by akliuxingyuan** 2023-09-27 13:47 UTC
