### ISSUE TITLE
Suggested web search engines

### ISSUE THREAD

**Issue by gallegonovato** [fork-maintainers/iceraven-browser#282] opened 2021-02-17 18:21 UTC
Good afternoon:

I take the opportunity, if I may. To see if it is possible that iceraven of origin includes search engines like seax, startpage or metager. Instead of twitter or wikipedia for example. Since you can search inside those webs or in them with any search engine. And the other three that I mention are so to speak more secure or in line with the privacy of our searches.

A hug and thank you for your time and help.

**Comment by CharmCityCrab** [comment] 2021-02-25 21:35
Duplicate of #244 with a few additional search engine suggestions.

Recommend merging into that existing issue and marking closed.

**Comment by interfect** [comment] 2021-03-05 02:09
Yes, I am going to close this as a duplicate of #244. If anyone wants to submit a PR to do this it would be very welcome!

**Closed by interfect** 2021-03-05 02:09 UTC
Labels: needs:triage
