### ISSUE TITLE
load custom XPI from filesystem or url

### ISSUE THREAD

**Issue by mgiampapa** [fork-maintainers/iceraven-browser#99] opened 2020-09-13 00:45 UTC
It looks like there is no way to load an arbitrary XPI for testing. XPI links are treated as downloads, and there doesn't seem to be any way to manually load them in the addon manager.

**Comment by mgiampapa** [comment] 2020-09-13 00:48
Probably, should close this. It's functionally the same as https://github.com/fork-maintainers/iceweasel/issues/31, didin't see that issue was open.

**Comment by interfect** [comment] 2020-09-15 05:08
Yeah, we want this, but this issue is a duplicate of #31, so I will close it.

**Closed as completed by interfect** 2020-09-15 05:08 UTC
