### ISSUE TITLE
[Bug] Enhanced Tracking Protection not working

### ISSUE THREAD

**Issue by HourGlassZ** [fork-maintainers/iceraven-browser#138] opened 2020-09-20 01:21 UTC
## Steps to reproduce
Enable Tracking Protection in settings.
Open a website.
Check Tracking Protection Status.
Always disable for this website. (Re-enable it then wait for it finished full refresh, still same)
### Expected behavior
Tracking Protection is enabled.
### Actual behavior
Tracking Protection always disabled.
### Device information

* Android device: SM-P350, crDroid Android 10
* Fenix version: iceraven-1.0.0 (Build #2015764505)
AC: 60.0.20200917130150, a1a5c582c
GV: 80.0.2-20200903001900
AS: 61.0.13

**Comment by bbigam** [comment] 2020-09-20 01:37
Duplicate of https://github.com/fork-maintainers/iceraven-browser/issues/86

**Closed as completed** 2020-09-20 01:39 UTC
Labels: needs:triage
