### ISSUE TITLE
Please add search button in bookmarks tab

### ISSUE THREAD

**Issue by CXVUSER** [fork-maintainers/iceraven-browser#211] opened 2020-10-09 01:00 UTC
Please add search button in bookmarks tab pls

**Comment by interfect** [comment] 2020-10-10 03:49
This is a partial dupe of #113 but this issue is more concise eo I will let this one win.

**Comment by akliuxingyuan** [comment] 2023-09-29 08:31
implemented in upstream

**Closed as completed by akliuxingyuan** 2023-09-29 08:31 UTC
Labels: enhancement, help wanted, good first issue, affects-upstream
