### ISSUE TITLE
Allow Sideloading Extensions

### ISSUE THREAD

**Issue by DraconicNEO** [fork-maintainers/iceraven-browser#438] opened 2022-02-13 07:58 UTC
### What is the user problem or growth opportunity you want to see solved?

The ability to install extensions on Firefox fenix and by extension IceRaven is extremely restricted. You need to set up collections and if your extension isn't on AMO or you can't install it at all. Even Fennec (old version of Firefox, not the imposter of a browser that is just another fenix fork now) had support for Sideloading extensions from xpi.

### How do you know that this problem exists today? Why is this important?

hours spent trying to install extensions from xpi as well as Multiple issues on official Mozilla GitHub (all ignored by Mozilla).

### Who will benefit from it?

Anyone who wants to install extensions from outside AMO.

**Comment by freebrowser1** [comment] 2022-02-14 13:58
Indeed would be very nice. Obviously at user's risk the extension does not work (properly).

**Comment by DraconicNEO** [comment] 2022-02-15 07:55
> Indeed would be very nice. Obviously at user's risk the extension does not work (properly).

Well considering it's not exactly something you can accidently do I feel like many people who will do it probably understand that risk.

**Comment by LeeBinder** [comment] 2022-04-13 20:34
That would be very nice indeed.

**Comment by LeeBinder** [comment] 2022-04-13 20:41
> Even Fennic (old version of Firefox, not the imposter of a browser that is just another fenix fork now) had support for Sideloading extensions from xpi.

@DraconicNEO do you mean Fenn**e**c rather than Fenn**i**c? Because Google does not know Fenn**i**c.

Can you please share a link to the apk of the browser version you're alluding to?

**Comment by DraconicNEO** [comment] 2022-04-13 23:23
> > Even Fennic (old version of Firefox, not the imposter of a browser that is just another fenix fork now) had support for Sideloading extensions from xpi.
> 
> @DraconicNEO do you mean Fenn**e**c rather than Fenn**i**c? Because Google does not know Fenn**i**c.
> 
> Can you please share a link to the apk of the browser version you're alluding to?

Yes I meant Fennec, it seems I misspelled it when I originally posted the issue. 

The imposter version I was talking about is [Fennec F-droid](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/) which is not actually based on Fennec anymore, hence why I'm calling them imposters since they are still trying to pass themselves off as Fennec but aren't in fact Fennec based.

**Comment by LeeBinder** [comment] 2022-04-14 18:16
Gotcha, now it makes sense, thanks for the clarification. Can you share a genuine link to Fennec (old version of Firefox)?

**Comment by DraconicNEO** [comment] 2022-04-15 05:02
> Gotcha, now it makes sense, thanks for the clarification. Can you share a genuine link to Fennec (old version of Firefox)?

Sure, I think [this one on apkmirror](https://www.apkmirror.com/apk/mozilla/fennec-f-droid/fennec-f-droid-67-0-2-release/) is one of the older Fennec versions (that supports addons without restrictions). I'd link an Fdroid version but they kind of deleted the old versions from there.

**Comment by LeeBinder** [comment] 2022-04-15 17:32
oh, that old. Sync doesn't work anymore with Firefox (& off-springs) v.6x.y.z, incl. [Waterfox 68.0A2](https://web.archive.org/web/20190620193005/https://play.google.com/store/apps/details?id=net.waterfox.waterfox). Anyway, thanks for the link.

I'll keep an eye on [SmartCookieWeb Preview](https://github.com/fork-maintainers/iceraven-browser/issues/371#issuecomment-1098458362) (my comment). It's dev [wrote](https://github.com/CookieJarApps/SmartCookieWeb-Preview/#sync) he'll add sync in a future update.

**Comment by interfect** [comment] 2022-07-11 02:13
Oh wow, it looks like SmartCookieWeb is just doing all their own app around GeckoView and not starting with Mozilla Fenix. That's honestly probably going to be a better approach.

Iceraven could maybe try and borrow some code for this, depending on the license?

But building the UI for this sounds like more real Android development than I actually am confident doing.

I'm going to close this as a duplicate of #371. If anyone who actually can build Android UI wants to build the UI out for this, we would just have to [do what they do](https://github.com/CookieJarApps/SmartCookieWeb-Preview/blob/669256f7df660f3d272d6f8822c2798cdbced507/app/src/main/java/com/cookiejarapps/android/smartcookieweb/settings/fragment/AdvancedSettingsFragment.kt#L130-L154) and get ahold of the Android Components `Engine` (which for us is like `context.components.core.engine` or something) and just call `installWebExtension` with an ID for it (which can be empty) and a URL to fetch it from.

**Closed as not planned by interfect** 2022-07-11 02:13 UTC
Labels: needs:triage
