### ISSUE TITLE
[Bug] Sync is Broken

### ISSUE THREAD

**Issue by L31FY** [fork-maintainers/iceraven-browser#253] opened 2020-12-09 00:15 UTC
## Steps to reproduce
Go to settings and attempt to sync data (or have it do so automatically as it is set to)

### Expected behavior
Sync works and my data syncs

### Actual behavior
Absolutely nothing seems to happen, and data does not sync

### Device information

* Android device: Samsung Galaxy S9, stock ROM
* Fenix version: Iceraven 1.4.0

**Comment by interfect** [comment] 2021-01-01 22:37
I don't think I can reproduce this. My sync has been working fine on 1.4.0. New tabs sent to Iceraven don't come in promptly (probably because we have ripped out all the server-side push stuff due to not having servers for it), but history and passwords have been syncing for me.

On my latest build, I can press the sync button to cause a sync to happen right then and it succeeds fine.

Maybe #257 will close this?

**Comment by L31FY** [comment] 2021-01-02 00:53
I looked into Nightly and I don't have it there but anywhere that I install Iceraven it won't sync so that's what I do know. I get the initial sync but past there no more history or bookmarks will sync forward from then (or to that instance either). This was previously also happening after the first "botched" Firefox update before I deleted it. They refused to accept my bug report however and accused me of not knowing how to click things then deleted the evidence however.

**Comment by Ja-Peter** [comment] 2021-01-20 16:38
Sync does not work for me either in Iceraven 1.5 (on Android 10). No automatic sync occurs and I cannot sync manually. Sync used to work in previous versions (1.4 and older).

**Comment by interfect** [comment] 2021-01-21 16:47
I'm having trouble replicating this. I just installed Iceraven 1.5 from the APK that Github built instead of my own, and sync still seems to work.

Are you signing in from 1.5, or were you signed in before upgrading?

Do you also have Mozilla Firefox signed in on the same device?

**Comment by Ja-Peter** [comment] 2021-01-21 16:56
I am signing in from Iceraven, I uninstalled Firefox before installing Iceraven.

**Comment by Ja-Peter** [comment] 2021-01-21 17:43
UPDATE: I re-installed Iceraven and sync works now!

**Closed as completed** 2023-09-27 14:08 UTC
Labels: bug
